# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ff2d5784ce9b0a008854c07616827706f4721f1084d4f6cb4295d4da4a8ab03a0bf85bd2cbd49b782dd5678cc97c1f32f733daf1fb3d43c11fb528e36c6ad12d

test:
  secret_key_base: 0064d84abfd1f6e9bfe7b7ab16cf431d4a22d65e4f4b41d92ade80006a521b9fd80b95aedc2aaa9e41a2c61502a7015a5a7db514264fd403e72ebe79a4b2a9f4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
